### PR TITLE
Pull request for Issue #10 and Feature #11

### PR DESCRIPTION
**Pull request by stildalf**
Fixed Issue #10 - Sub-Collection exports.
Allowed for Feature #11:
- Changed to SheetJS for XLSX and CSV imports/exports
- Allow selecting multiple/all collections for import/export
- Exports to CSV and XLSX splits collections into indexed files/sheets
- Field encoders/decoders for special types such as GeoPoint, Reference, Timestamp, Null, etc.

### CODE REVIEW

**Comment by stildalf** [comment]
Added to the PR:
- Brought back the old test files.
- Tested them for backwards compatibility. Fixed some issues with JSON imports. 
- Reorganised the test files into the samples directory.

**Comment by talas9** [comment]
Still, sub-collections are nested outside of the  parent collection

**Comment by codediodeio** [comment]
Awesome, thank you for putting this together @stildalf

**Comment by Robin-AF** [comment]
@stildalf Thanks for this MR!

I seem to run into problems regarding the `isEncodingType` on `BooleanFH`.

I made a xlsx sheet with a `FALSE` value but that gets encoded to 0 and `TRUE` gets encoded to `1` (numbers) instead of the true value (Boolean). any ideas what might be causing this?

**Pull request merged**
